# $FreeBSD: src/sys/modules/if_vlan/Makefile,v 1.6 2008/12/02 21:37:28 bz Exp $

.PATH: ${.CURDIR}/../../net

KMOD=	if_vlan
SRCS=	if_vlan.c
SRCS+=	opt_inet.h opt_vlan.h opt_route.h

.include <bsd.kmod.mk>
