# $FreeBSD: src/sys/modules/mac_lomac/Makefile,v 1.2 2009/06/06 17:01:44 rwatson Exp $

.PATH: ${.CURDIR}/../../security/mac_lomac

KMOD=	mac_lomac
SRCS=	vnode_if.h \
	mac_lomac.c

.include <bsd.kmod.mk>
