# $FreeBSD: src/sys/modules/ahci/Makefile,v 1.1 2009/07/10 08:18:08 scottl Exp $

.PATH: ${.CURDIR}/../../dev/ahci

KMOD=	ahci
SRCS=	ahci.c ahci.h device_if.h bus_if.h pci_if.h opt_cam.h

.include <bsd.kmod.mk>
