# $FreeBSD: src/sys/modules/amdsbwd/Makefile,v 1.1 2009/11/30 11:44:03 avg Exp $

.PATH:  ${.CURDIR}/../../dev/amdsbwd
KMOD    = amdsbwd
SRCS    = amdsbwd.c
SRCS    += device_if.h bus_if.h pci_if.h isa_if.h

.include <bsd.kmod.mk>
