# $FreeBSD: src/sys/modules/sysvipc/sysvshm/Makefile,v 1.6 2009/06/06 17:01:44 rwatson Exp $

.PATH: ${.CURDIR}/../../../kern

KMOD=	sysvshm
SRCS=	sysv_shm.c opt_sysvipc.h opt_compat.h

.include <bsd.kmod.mk>
