# $FreeBSD: src/sys/boot/i386/Makefile,v 1.22 2007/10/24 21:32:58 jhb Exp $

SUBDIR=		mbr pmbr boot0 boot0sio btx boot2 cdboot gptboot kgzldr \
		libi386 libfirewire loader

# special boot programs, 'self-extracting boot2+loader'
SUBDIR+=	pxeldr

.include <bsd.subdir.mk>
