# $FreeBSD: src/sys/modules/sge/Makefile,v 1.1 2010/04/14 20:45:33 yongari Exp $

.PATH: ${.CURDIR}/../../dev/sge

KMOD=	if_sge
SRCS=	if_sge.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
