# $FreeBSD: src/sys/modules/libalias/libalias/Makefile,v 1.3 2009/02/07 18:49:42 piso Exp $

.PATH: ${.CURDIR}/../../../netinet/libalias

KMOD=	libalias
SRCS=	alias.c alias_db.c alias_proxy.c alias_util.c alias_mod.c alias_sctp.c

.include <bsd.kmod.mk>
