# $FreeBSD: src/sys/modules/geom/geom_sched/gsched_rr/Makefile,v 1.1 2010/04/12 16:37:45 luigi Exp $

KMOD=   gsched_rr
SRCS=   gs_rr.c
# hash.h on 6.x has a (char *) cast on a const pointer
#CWARNFLAGS=

# ../Makefile.inc automatically included
.include <bsd.kmod.mk>
