# $FreeBSD: src/sys/modules/ata/atapci/chipsets/Makefile,v 1.1 2008/10/09 12:56:57 sos Exp $

SUBDIR += ataacard ataacerlabs ataadaptec ataahci ataamd ataati atacenatek atacypress atacyrix atahighpoint ataintel ataite atajmicron atamarvell atamicron atanational atanetcell atanvidia atapromise ataserverworks atasiliconimage atasis atavia

.include <bsd.subdir.mk>
