# $FreeBSD: src/sys/modules/bios/smbios/Makefile,v 1.2 2010/02/25 14:13:39 attilio Exp $
#

.PATH:  ${.CURDIR}/../../../x86/bios

KMOD=	smbios
SRCS=	smbios.c \
	bus_if.h device_if.h

.include <bsd.kmod.mk>
