# $FreeBSD: src/sys/modules/epic/Makefile,v 1.1 2010/01/10 15:44:48 marius Exp $

.PATH: ${.CURDIR}/../../sparc64/ebus

KMOD=	epic
SRCS=	device_if.h epic.c bus_if.h ofw_bus_if.h

.include <bsd.kmod.mk>
