# $FreeBSD: src/sys/modules/iwn/Makefile,v 1.2 2008/05/22 21:53:15 sam Exp $

.PATH:  ${.CURDIR}/../../dev/iwn

KMOD    = if_iwn
SRCS    = if_iwn.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
