# $FreeBSD: src/sys/modules/acpi/acpi_dock/Makefile,v 1.2 2009/06/05 18:44:36 jkim Exp $

.PATH:		${.CURDIR}/../../../dev/acpica
KMOD=		acpi_dock
SRCS=		acpi_dock.c opt_acpi.h device_if.h bus_if.h acpi_if.h
SRCS+=		opt_ddb.h

.include <bsd.kmod.mk>
