# $FreeBSD: src/sys/modules/geom/geom_part/Makefile,v 1.3 2008/03/28 17:58:55 marcel Exp $

SUBDIR=	geom_part_apm \
	geom_part_bsd \
	geom_part_gpt \
	geom_part_mbr \
	geom_part_pc98 \
	geom_part_vtoc8

.include <bsd.subdir.mk>
