# $FreeBSD: src/sys/modules/geom/geom_part/Makefile,v 1.4 2009/02/08 23:51:44 marcel Exp $

SUBDIR=	geom_part_apm \
	geom_part_bsd \
	geom_part_ebr \
	geom_part_gpt \
	geom_part_mbr \
	geom_part_pc98 \
	geom_part_vtoc8

.include <bsd.subdir.mk>
