# $FreeBSD: src/sys/modules/netgraph/atm/atm/Makefile,v 1.3 2009/06/08 19:57:35 bz Exp $
#
# Author: Harti Brandt <harti@freebsd.org>
#
.PATH: ${.CURDIR}/../../../../netgraph/atm

KMOD=	ng_atm
SRCS=	ng_atm.c
# CFLAGS+= -DNGATM_DEBUG

.include <bsd.kmod.mk>
