# $FreeBSD: src/sys/modules/netgraph/atm/atm/Makefile,v 1.2 2008/12/02 21:37:28 bz Exp $
#
# Author: Harti Brandt <harti@freebsd.org>
#
.PATH: ${.CURDIR}/../../../../netgraph/atm

KMOD=	ng_atm
SRCS=	ng_atm.c opt_route.h
# CFLAGS+= -DNGATM_DEBUG

.include <bsd.kmod.mk>
