# $FreeBSD: src/sys/modules/ichwd/Makefile,v 1.2 2009/11/07 11:41:23 avg Exp $

.PATH: ${.CURDIR}/../../dev/ichwd

KMOD=	ichwd
SRCS=	ichwd.c device_if.h bus_if.h pci_if.h isa_if.h

.include <bsd.kmod.mk>
