# $FreeBSD: src/sys/modules/siis/Makefile,v 1.1 2009/07/21 12:32:46 mav Exp $

.PATH: ${.CURDIR}/../../dev/siis

KMOD=	siis
SRCS=	siis.c siis.h device_if.h bus_if.h pci_if.h opt_cam.h

.include <bsd.kmod.mk>
