# $FreeBSD: src/sys/modules/geom/geom_sched/gs_sched/Makefile,v 1.1 2010/04/12 16:37:45 luigi Exp $
KMOD=   geom_sched
SRCS=   g_sched.c subr_disk.c

# ../Makefile.inc automatically included
.include <bsd.kmod.mk>
