# $FreeBSD: src/sys/modules/age/Makefile,v 1.1 2008/05/19 01:53:47 yongari Exp $

.PATH: ${.CURDIR}/../../dev/age

KMOD=	if_age
SRCS=	if_age.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
