# $FreeBSD: src/sys/modules/bwn/Makefile,v 1.1 2010/02/16 01:44:14 weongyo Exp $

.PATH: ${.CURDIR}/../../dev/bwn

KMOD=	if_bwn
SRCS=	if_bwn.c if_bwnreg.h if_bwnvar.h
SRCS+=	device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
