# $FreeBSD: src/sys/boot/i386/zfsloader/Makefile,v 1.2 2010/08/31 19:01:12 delphij Exp $

.PATH:	${.CURDIR}/../loader

LOADER=		zfsloader
NEWVERSWHAT=	"ZFS enabled bootstrap loader" x86
LOADER_ZFS_SUPPORT=yes
LOADER_ONLY=	yes
NO_MAN=		yes

.include "${.CURDIR}/../loader/Makefile"

