# $FreeBSD: src/sys/modules/alc/Makefile,v 1.1 2009/06/10 02:07:58 yongari Exp $

.PATH: ${.CURDIR}/../../dev/alc

KMOD=	if_alc
SRCS=	if_alc.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
