# $FreeBSD: src/sys/modules/geom/geom_sched/Makefile.inc,v 1.1 2010/04/12 16:37:45 luigi Exp $
# included by geom_sched children

.PATH: ${.CURDIR}/../../../../geom/sched

# 6.x needs this path
#CFLAGS += -I${.CURDIR}/../../../../geom/sched

# .include <bsd.kmod.mk>
