# $FreeBSD: src/sys/modules/jme/Makefile,v 1.1 2008/05/27 01:54:45 yongari Exp $

.PATH: ${.CURDIR}/../../dev/jme

KMOD=	if_jme
SRCS=	if_jme.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
