# $FreeBSD: src/sys/modules/geom/geom_linux_lvm/Makefile,v 1.1 2008/02/20 07:50:12 thompsa Exp $

.PATH: ${.CURDIR}/../../../geom/linux_lvm

KMOD=	geom_linux_lvm
SRCS=	g_linux_lvm.c

.include <bsd.kmod.mk>
