#	$FreeBSD: src/sys/modules/acpi/acpi_video/Makefile,v 1.8 2009/06/05 18:44:36 jkim Exp $

.PATH:	${.CURDIR}/../../../dev/acpica

KMOD=	acpi_video
SRCS=	acpi_video.c
SRCS+=	opt_acpi.h acpi_if.h bus_if.h device_if.h

.include <bsd.kmod.mk>
