# Conexant/Intersil PrismGT SoftMAC(GW3887) USB devices
#
# $FreeBSD: src/sys/modules/upgt/Makefile,v 1.1 2008/08/11 03:57:31 weongyo Exp $

.PATH: ${.CURDIR}/../../dev/usb

KMOD    = if_upgt
SRCS    = if_upgt.c opt_usb.h device_if.h bus_if.h usbdevs.h

.include <bsd.kmod.mk>
