# $FreeBSD: src/sys/modules/geom/geom_mountver/Makefile,v 1.1 2010/01/16 09:52:49 trasz Exp $

.PATH: ${.CURDIR}/../../../geom/mountver

KMOD=	geom_mountver
SRCS=	g_mountver.c

.include <bsd.kmod.mk>
