# $FreeBSD: src/sys/modules/acpi/acpi_panasonic/Makefile,v 1.5 2009/06/05 18:44:36 jkim Exp $

.PATH:	${.CURDIR}/../../../dev/acpi_support

KMOD=	acpi_panasonic
SRCS=	acpi_panasonic.c opt_acpi.h acpi_if.h bus_if.h device_if.h

.include <bsd.kmod.mk>
