# $FreeBSD: src/sys/modules/wpi/Makefile,v 1.3 2008/03/27 20:38:03 antoine Exp $

.PATH:  ${.CURDIR}/../../dev/wpi

KMOD    = if_wpi
SRCS    = if_wpi.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
