# $FreeBSD: src/sys/modules/acpi/acpi_ibm/Makefile,v 1.4 2009/06/05 18:44:36 jkim Exp $

.PATH:		${.CURDIR}/../../../dev/acpi_support
KMOD=		acpi_ibm
SRCS=		acpi_ibm.c opt_acpi.h device_if.h bus_if.h acpi_if.h
SRCS+=		opt_ddb.h

.include <bsd.kmod.mk>
