# $FreeBSD: src/sys/modules/ata/atapci/chipsets/ataacard/Makefile,v 1.1 2008/10/09 12:56:57 sos Exp $

.PATH: ${.CURDIR}/../../../../../dev/ata/chipsets

KMOD=	ataacard
SRCS=	ata-acard.c
SRCS+=  opt_ata.h ata_if.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>

