# $FreeBSD: src/sys/modules/alq/Makefile,v 1.1 2010/03/31 03:58:57 lstewart Exp $

.include <bsd.own.mk>

.PATH:  ${.CURDIR}/../../kern
KMOD=	alq
SRCS=	opt_mac.h vnode_if.h kern_alq.c

.include <bsd.kmod.mk>
