# $FreeBSD: src/sys/modules/ksyms/Makefile,v 1.1 2009/05/26 21:39:09 sson Exp $

.PATH: ${.CURDIR}/../../dev/ksyms

KMOD=  ksyms   
SRCS=  ksyms.c linker_if.h

MFILES= kern/linker_if.m

.include <bsd.kmod.mk>
