# $FreeBSD: src/sys/modules/ae/Makefile,v 1.3 2008/12/02 21:37:28 bz Exp $

.PATH: ${.CURDIR}/../../dev/ae

KMOD=	if_ae
SRCS=	if_ae.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
